config/routes.rb
Rails.application.routes.draw do
  resources :doctrees, :folders, :doc_permissions, :projects, :teams, :documents, :users
  resources :projects do
    resources :documents, to: 'documents#show'
    resources :folders, to: 'projects#folder'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: 'registrations' }, path: "accounts", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'profile', 
    sign_up: 'sign_up' 
  }

  #Static pages
  root "static_pages#home"

  #Dashboard
  get "dashboard" => "dashboard#index" 

  #PDF Viewer
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  #carrierwave file view
  get '/storage/document/doc_file/:id/:basename.:extension' => 'documents#download'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index]
  after_filter :verify_policy_scoped, :only => :index

  def index
    @user = current_user
    @assets = policy_scope(Asset).approved.group_by(&:project).take(2)
    @documents = policy_scope(Document).limit(10)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_doc_boxes.html.haml
.col-xs-12.doc-box
  .col-xs-12
    %table.table.table-striped
      - @documents.each do |d|
        %tr
          %td
            %ul.list-unstyled
              %li.date= d.created_at.strftime("%b %d, %Y")
              %li
                = link_to doc_title(d), document_path(d)

app/views/dashboard/_project_boxes.html.haml
.col-xs-12.project-box
  .col-xs-12.col-sm-3.col-md-2
    =link_to project_path(p.project) do
      =image_tag(p.project.thumbnail) 
  .col-xs-12.col-sm-9.col-md-10
    .col-xs-12.project-box-header
      %h2
        %span.pretitle
          PROJECT:
        =link_to p.project.title, project_path(p.project)
    .col-xs-12
    %ul.list-unstyled.project-box-list
      %li PROJECT MANAGERS:
      %li DOCUMENTS: #{p.project.documents.length}
      %li MEMBERS: #{p.project.stakeholders.length}
      %li LAST ACTIVITY:
      %li NEXT ACTION DATE:
  .col-xs-12
    %table.table.table-striped
      -p.project.documents.each do |d|
        %tr
          %td
            = link_to doc_title(d), project_document_url(p.project,d)
          %td.view-link
            = link_to pdfjs.full_path(file: document_url(d)) do
              -filetype_icon(d.file_content_type)

app/views/dashboard/index.html.haml
- provide(:title, 'DASHBOARD')
.container
  .row.row-eq-height
    .col-sm.12.col-md-10.col-md-push-2.primary
      .title
        %h1
          DASHBOARD
      .primary-content
        .col-xs-12.col-md-9
          -unless @assets.empty?
            .project-panel
              %h4
                %i.fa.fa-sitemap
                PROJECTS
              -@assets.each do |p, docs|
                = render partial: 'shared/project_box', locals: {p: p, docs: docs}
        .col-xs-12.col-md-3
          -unless @assets.empty?
            .doc-panel
              %h4
                %i.fa.fa-file-text
                RECENT DOCUMENTS
              %table.table-striped
                = render partial: 'shared/sb_document_module'
    =render 'shared/left_sidebar'

app/views/dashboard/landing.html.haml
- provide(:title, 'DASHBOARD')
.container
  .row.row-eq-height
    .col-sm.12.col-md-10.col-md-push-2.primary
      .title
        %h1
          DASHBOARD
      .primary-content
        .col-xs-12.col-md-9
          -if @projects.exists?
            .project-panel
              %h4
                %i.fa.fa-sitemap
                PROJECTS
              - @projects.each do |p|
                = render partial: 'project_boxes', locals: {p: p}
        .col-xs-12.col-md-3
          -if @documents.exists?
            .doc-panel
              %h4
                %i.fa.fa-file-text
                RECENT DOCUMENTS
              = render partial: 'doc_boxes'
    =render 'layouts/left_sidebar'