config/routes.rb
Rails.application.routes.draw do
  resources :doctrees, :folders, :doc_permissions, :projects, :teams, :documents, :users
  resources :projects do
    resources :documents, to: 'documents#show'
    resources :folders, to: 'projects#folder'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: 'registrations' }, path: "accounts", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'profile', 
    sign_up: 'sign_up' 
  }

  #Static pages
  root "static_pages#home"

  #Dashboard
  get "dashboard" => "dashboard#index" 

  #PDF Viewer
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  #carrierwave file view
  get '/storage/document/doc_file/:id/:basename.:extension' => 'documents#download'
end

app/models/folder.rb
# == Schema Information
#
# Table name: folders
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer
#

class Folder < ActiveRecord::Base
  belongs_to :project
  has_many :documents, through: :doctrees
  has_many :doctrees, dependent: :delete_all
  validates :title, presence: true
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  def slug_candidates
    [
      [:project_id, :title],
      [:project_id, :id, :title]
    ]
  end
end

app/controllers/folders_controller.rb
# == Schema Information
#
# Table name: folders
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer
#

class FoldersController < InheritedResources::Base
  before_action :set_user
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :file_documents]
  before_action :authenticate_user!

  def new
    @folder = @folder.new
  end

  def create
    @project = Project.find(params[:folder][:project_id])
    if FolderPolicy.new(@user, @project).update? 
      @folder = Folders::CreateFolder.call(@user, @project, folder_params)
      if @folder.persisted?
        redirect_to @project, notice: "Folder successfully created."
      else
        render action: "new"
      end
    else
      redirect_to @project, alert: "Insufficient permissions"
    end
  end

  def file_documents
    authorize @folder
  end

  def update
    authorize @folder
    if @folder.update(folder_params)
      redirect_to folder_path(@folder)
    else
      render :edit
    end
  end

  private
  def set_user
    @user = current_user
  end

  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:title, :slug, :project_id, :created_by, document_ids:[])
  end
end

app/helpers/folders_helper.rb
# == Schema Information
#
# Table name: folders
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer
#

module FoldersHelper
end

app/views/folders/_form.html.haml
- @project_id = @folder.project_id || project_id
.container
  .row
    .col-sm-12
      %h2 ADD FOLDER
      = simple_form_for(@folder) do |f|
        .form-inputs
          = f.hidden_field :project_id, value: @project_id
        .form-inputs
          = f.input :title
        .form-actions
          = f.button :submit

app/views/folders/edit.html.haml
%h1 Editing folder

= render 'form'

= link_to 'Show', @folder
\|
= link_to 'Back', folders_path

app/views/folders/index.html.haml
%h1 Listing folders

%table
  %thead
    %tr
      %th Title
      %th Slug
      %th
      %th
      %th

  %tbody
    - @folders.each do |folder|
      %tr
        %td= folder.title
        %td= folder.slug
        %td= link_to 'Show', folder
        %td= link_to 'Edit', edit_folder_path(folder)
        %td= link_to 'Destroy', folder, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Folder', new_folder_path

app/views/folders/new.html.haml
%h1 New folder

= render 'form'

= link_to 'Back', folders_path

app/views/folders/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @folder.title

= link_to 'Edit', edit_folder_path(@folder)
\|
= link_to 'Back', folders_path