config/routes.rb
Rails.application.routes.draw do
  resources :doctrees, :folders, :doc_permissions, :projects, :teams, :documents, :users
  resources :projects do
    resources :documents, to: 'documents#show'
    resources :folders, to: 'projects#folder'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: 'registrations' }, path: "accounts", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'profile', 
    sign_up: 'sign_up' 
  }

  #Static pages
  root "static_pages#home"

  #Dashboard
  get "dashboard" => "dashboard#index" 

  #PDF Viewer
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  #carrierwave file view
  get '/storage/document/doc_file/:id/:basename.:extension' => 'documents#download'
end

app/views/shared/_doc_table.html.haml
.col-xs-12.project-box
  .col-xs-12.col-sm-3.col-md-2
    =link_to project_path(p) do
      =image_tag(p.thumbnail) 
  .col-xs-12.col-sm-9.col-md-10
    .col-xs-12.project-box-header
      %h2
        %span.pretitle
          PROJECT:
        =link_to p.title, project_path(p)
    .col-xs-12
      %ul.list-unstyled.project-box-list
        %li PROJECT MANAGERS:
        %li DOCUMENTS: #{p.documents.length}
        %li MEMBERS: #{p.stakeholders.length}
        %li LAST ACTIVITY:
        %li NEXT ACTION DATE:
  .col-xs-12
    %table.table.table-striped
      -p.documents.each do |d|
        %tr
          %td
            = link_to doc_title(d), project_document_url(p,d)
          %td.view-link
            = link_to pdfjs.full_path(file: document_url(d)) do
              -filetype_icon(d.file_content_type)

app/views/shared/_footer.html.haml
%footer
  .col-xs-12.col-sm-4
    datarooms
  .col-xs-12.col-sm-4
    datarooms
  .col-xs-12.col-sm-4
    datarooms

app/views/shared/_header.html.haml
%header
  -if @user
    .background-image{style: "background-image: url(#{@user.avatar.header})"}

app/views/shared/_left_sidebar.html.haml
.col-sm-12.col-md-2.col-md-pull-10.sidebar-left
  =sidebar_modules(controller_name, action_name)

app/views/shared/_project_box.html.haml
.col-xs-12.project-box
  .col-xs-12.col-sm-3.col-md-2
    =link_to project_path(p) do
      =image_tag(p.thumbnail) 
  .col-xs-12.col-sm-9.col-md-10
    .col-xs-12.project-box-header
      %h2
        %span.pretitle
          PROJECT:
        =link_to p.title, project_path(p)
    .col-xs-12
      %ul.list-unstyled.project-box-list
        %li PROJECT MANAGERS:
        %li DOCUMENTS: #{docs.count} 
        %li MEMBERS: #{p.stakeholders.count} 
        %li LAST ACTIVITY:
        %li NEXT ACTION DATE:
  .col-xs-12
    %table.table.table-striped
      -docs.first(5).each do |d|
        %tr
          %td
            = link_to doc_title(d.document), project_document_url(p,d.document)
          %td.view-link
            = link_to pdfjs.full_path(file: document_url(d.document)) do
              -filetype_icon(d.document.file_content_type)

app/views/shared/_sb_document_module.html.haml
-@documents.each do |d|
  %tr
    %td 
      %span= d.created_at
      = d.title

app/views/shared/_sb_members_module.html.haml
.sidebar-box.members.panel.panel-default
  .panel-heading.title
    %h2
      %i.fa.fa-users
      MEMBERS
  .panel-body
    .input-group
    %table.table.table-striped.table-hover
      %tbody
        -@team.memberships.each do |t|
          %tr
            %td
              =link_to image_tag(t.user.avatar, class: 'img-circle'), user_path(t.user)
            %td.member-name
              =link_to t.user.name, user_path(t.user)
              -admin_icon(t)

app/views/shared/_sb_notifications_module.html.haml
.sidebar-box.notifications.panel.panel-default
  .panel-heading.title
    %h2
      NOTIFICATIONS
  .panel-body
    %table.table.table-striped.table-hover
      %tbody
        %tr
          %td 1
        %tr
          %td 1
        %tr
          %td 1
        %tr
          %td 1

app/views/shared/_sb_project_module.html.haml
.sidebar-box.project
  %ul.list-unstyled
    %li
      = link_to image_tag(@project.thumbnail), edit_project_path(@project)
    %h2
      %li.username= link_to @project.title, edit_project_path(@project)
    %li
      Documents: 
      = @documents.length
    %li
      Members: 
      = @project.stakeholders.length

app/views/shared/_sb_stakeholders_module.html.haml
.sidebar-box.members.panel.panel-default
  .panel-heading.title
    %h3
      %i.fa.fa-users
      MEMBERS
  .panel-body
    %table.table.table-striped.table-hover
      -if policy(@project).update?
        %ul.list-inline
          %li edit
      %tbody
        -@project.stakeholders.each do |s|
          %tr
            %td
              =link_to image_tag(s.user.avatar, class: 'img-circle'), user_path(s.user)
            %td.member-name
              =link_to s.user.name, user_path(s.user)
              -admin_icon(s)

app/views/shared/_sb_user_module.html.haml
.sidebar-box.user
  %ul.list-unstyled
    %li
      = link_to image_tag(current_user.avatar, class: 'img-circle'), current_user
    %h3
      %li.username= link_to current_user.name.upcase, current_user
    %li.email= current_user.email
    %li= current_user.title
    %li= current_user.company

app/views/shared/_side_nav.html.haml
.sidebar{:role => "navigation"}
  .sidebar-nav.navbar-collapse
    %ul#side-menu.nav
      %li.sidebar-search
        .input-group.custom-search-form
          %input.form-control{:placeholder => "Search...", :type => "text"}/
          %span.input-group-btn
            %button.btn.btn-default{:type => "button"}
              %i.fa.fa-search
        / /input-group
      = image_tag(current_user.avatar, class: 'img-circle img-responsive')
      %h4
        =current_user.username
      %h5
        =current_user.title
      %h5
        =current_user.company
      =link_to "Edit profile", edit_user_registration_path
      %li
        =link_to dashboard_path do
          %i.fa.fa-th
          Dashboard
      - if @proj_list.size > 1
        %li.dropdown
          %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"} 
          %i.fa.fa-tasks
            Projects
            %b.caret
            %ul.dropdown-menu{"role" => "menu"}
              %li
                = link_to "See all", projects_path
                - @proj_list.each do |p|
                  %li= link_to p.title, project_path(p)
      - else  
        %li
          =link_to projects_path do
            %i.fa.fa-tasks
            Projects
          %li
            =link_to documents_path do
              %i.fa.fa-file-text-o
              Documents
          %li
            =link_to dashboard_path do
              %i.fa.fa-users
              Teams

app/views/shared/_team_box.html.haml
.sidebar-box.team
  %ul.list-unstyled
    %li
      = link_to image_tag(@team.thumbnail), edit_team_path(@team)
    %h2
      %li.username= link_to @team.title, edit_team_path(@team)
    %li
      Members: 
      = @team.memberships.length

app/views/shared/_user_box.html.haml
.sidebar-box.user
  %ul.list-unstyled
    %li
      = link_to image_tag(current_user.avatar, class: 'img-circle'), current_user
    %h2
      %li.username= link_to current_user.name.upcase, current_user
    %li.email= current_user.email
    %li= current_user.title
    %li= current_user.company