config/routes.rb
Rails.application.routes.draw do
  resources :doctrees, :folders, :doc_permissions, :projects, :teams, :documents, :users
  resources :projects do
    resources :documents, to: 'documents#show'
    resources :folders, to: 'projects#folder'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: 'registrations' }, path: "accounts", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'profile', 
    sign_up: 'sign_up' 
  }

  #Static pages
  root "static_pages#home"

  #Dashboard
  get "dashboard" => "dashboard#index" 

  #PDF Viewer
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  #carrierwave file view
  get '/storage/document/doc_file/:id/:basename.:extension' => 'documents#download'
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                :integer          not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  doc_file          :string(255)
#  file_content_type :string(255)
#  file_size         :integer
#  file_updated_at   :datetime
#  description       :text(65535)
#  user_id           :integer
#  title             :string(255)
#  original_filename :string(255)
#

class Document < ActiveRecord::Base
  include Sortable
  before_create :randomize_id
  has_many :users, through: :doc_permissions
  has_many :doc_permissions, dependent: :delete_all
  has_many :projects, through: :assets
  has_many :assets, dependent: :delete_all
  has_many :folders, through: :doctrees
  has_many :doctrees, dependent: :delete_all
  belongs_to :user

  validates :doc_file, presence: true
  validate :legit_filetype
  mount_uploader :doc_file, DocumentUploader
  before_save :save_doc_metadata

  private
  # Use file to check if filetype is acceptable (pdf,doc) and is what it claims to be
  def legit_filetype
    Cocaine::CommandLine.new('file', '-b --mime-type :file').run(file: "#{self.doc_file}").chomp.in?(['application/pdf', 'application/doc']) ? self.file_content_type = doc_file.file.content_type : errors.add(:document, 'Invalid content type')
  end

  def save_doc_metadata
    if doc_file.present? && doc_file_changed?
      self.file_size = doc_file.file.size
    end
  end

  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000_000)
    end while Document.where(id: self.id).exists?
  end
end

app/controllers/documents_controller.rb
# == Schema Information
#
# Table name: documents
#
#  id                :integer          not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  doc_file          :string(255)
#  file_content_type :string(255)
#  file_size         :integer
#  file_updated_at   :datetime
#  description       :text(65535)
#  user_id           :integer
#  title             :string(255)
#  original_filename :string(255)
#

class DocumentsController < ApplicationController  
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy, :permissions, :download]
  before_action :set_user
  after_action :verify_authorized, except: [:index, :new, :create]
  after_filter :verify_policy_scoped, :only => :index

  def index
    @documents = policy_scope(Document)
  end

  def show
    authorize @document
    if params[:project_id]
      @project = Project.friendly.find(params[:project_id])
    end
  end

  def new
    @document = @user.documents.new
    @projects = policy_scope(Project)
  end

  def create
    @document = Documents::CreateDocument.call(@user, document_params)
    if @document.persisted?
      redirect_to @document, notice: "Document successfully created."
    else
      render action: "new"
    end
  end

  def edit
    authorize @document, :update?
  end

  def update
    if @document.update(document_params)
      redirect_to documents_path
    else
      render :edit
    end
  end

  def destroy
    authorize @document
    @document.destroy
    redirect_to :back
  end

  def download
    authorize @document
    send_file "#{@document.doc_file.path}", disposition: 'attachment', x_sendfile: true
  end

  private
  def set_user
    @user = current_user
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:doc_file, :title, :description, :user_id, :document_id, :abilities, :expiration, :approved, project_ids: [])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper

  # Format title, new if exists, orig if not
  def doc_title(d) 
    if d.title.empty? 
      d.original_filename.gsub(/_/, ' ').upcase
    else
      d.title.upcase
    end
  end

  # Add uploader (unless current_user), created date and size info
  def doc_meta(d)
    uploader = d.user == current_user ? '' : 'by '+d.user.upcase+', '
    "#{uploader}#{d.created_at.strftime("%b %d, %Y")}, (#{number_to_human_size(d.file_size)})"
  end

  # The next 3 populate documents toolbar based on permissions (view, dl, rm)
  def doc_toolbar_view(d)
    if policy(d).show?
      content_tag(:li, class: '') do
        link_to pdfjs.full_path(file: document_url(d)) do
          haml_tag :i, class: "fa fa-eye"
        end
      end
    end
  end
  def doc_toolbar_download(d)
    if policy(d).download?
      content_tag(:li, class: '') do
        link_to document_url(d) do
          haml_tag :i, class: "fa fa-download"
        end
      end
    end
  end
  def doc_toolbar_delete(d)
    if policy(d).destroy?
      content_tag(:li, class: '') do
        link_to document_path(d), :method => :delete, :data => { :confirm => 'Are you sure?' }, "data-original-title" => "Delete" do
          haml_tag :i, class: "fa fa-trash"
        end
      end
    end
  end



end

app/views/documents/_doc_list.html.haml
.col-xs-12.doc-box
  - if @folders.exists?
    %ul.list-unstyled
      - @folders.each do |f|
        %li.folder
          =link_to '#' do
            %i.fa.fa-folder
            =f.title
  %ul.list-unstyled.ui-selectable#selectable
    - @documents.each do |d|
      %li.ui-widget-content.ui-selectee
        %span.doc-meta= d.document.created_at.strftime("%b %d, %Y")
        %span= link_to doc_title(d.document), document_path(d.document)

app/views/documents/_doc_toolbar.html.haml
=form_tag(method: 'file_documents', controller: 'folders') do
  %ul.list-inline.project-toolbar
    -if policy(@project).update?
      %li.nav-item.btn-group
        %a.dropdown-toggle.nav-link#projectMenu{'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false', :type => 'button'}
          %i.fa.fa-plus
          NEW
        %ul.dropdown-menu{'aria-labelledby' => 'projectMenu'}
          %li= link_to 'DOCUMENT', '#', :data => {:target => ".new-document-modal", :toggle => "modal"}
          - if policy(@project).update? 
            %li= link_to 'FOLDER', '#', :data => {:target => ".new-folder-modal", :toggle => "modal"}
        - if @folders.exists? && policy(@project).update?
          %li.nav-item.btn-group
            %a.dropdown-toggle.nav-link#addToFolder{'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false', :type => 'button'}
              %i.fa.fa-folder
              ADD TO FOLDER
            %ul.dropdown-menu{'aria-labelledby' => 'addToFolder'}
              -@folders.each do |f|
                %li= link_to f.title, folder_path(f)
          %li SORT
          %li SELECT ALL

app/views/documents/_form.html.haml
- project_id ||= session[:project_id]
.form-wrapper
  = simple_form_for @document, html: { multipart: true } do |f|
    .form-group
      = f.hidden_field :project_id, value: project_id
      = f.file_field :doc_file
      .form-group
        = f.association :projects, as: :check_boxes, checked: (defined?(project_id)? project_id : '') 
    .form-group.text-center
      = f.input :title
    .form-group.text-center
      = f.input :description
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/documents/_permissions_table.html.haml
%tr
  %td
    = image_tag(p.user.avatar, class: 'img-circle')
  %td
    = p.user.username
    (#{p.user.email})
  %td= p.user.email
  %td= p.user.id
  %td= p.abilities

app/views/documents/edit.html.haml
.container
  .row
    .col-lg-12
      %h1 Editing Document
      = render 'form'
      = link_to 'Show', @document
      |
      = link_to 'Back', documents_path

app/views/documents/index.html.haml
- provide(:title, 'DOCUMENTS')
.container
  .row.row-eq-height
    .col-sm.12.col-md-10.col-md-push-2.primary
      .title
        %h1
          DOCUMENTS
      .primary-content
        .col-xs-12
          = link_to "NEW", new_document_path
          -if @documents.exists?
            %table.table.table-striped
              -@documents.each do |d|
                %tr
                  %td
                    %span.doc-meta= doc_meta(d)
                    = link_to doc_title(d), document_path(d)
                  %td
                    %ul.list-inline
                      =doc_toolbar_view(d)
                      =doc_toolbar_download(d)
                      =doc_toolbar_delete(d)
        .col-xs-12.col-md-3
    =render 'shared/left_sidebar'

app/views/documents/new.html.haml
%h1 New document
= render 'form'
= link_to 'Back', documents_path

app/views/documents/show.html.haml
- @project ||= false
- provide(:title, 'DOCUMENTS: '+@document.title.upcase)
.container
  .row.row-eq-height
    .col-sm-12.primary
      .title
        %h1
          DOCUMENT:
          =doc_title(@document)
      .description
        - unless @project == false
          PROJECT: 
          =link_to @project.title.upcase, project_path(@project)
        =@document.description
      .edit_link
        - if policy(@document).update?
          =link_to 'Edit', edit_document_path(@document)
      .primary-content
        =doc_meta(@document)